language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - coverage run runtests.py
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
